### ISSUE TITLE
Could I get that in Cornflower blue?

### ISSUE THREAD

**Issue by vinchinzu** [kennycason/number_visualization#1]

**Comment by kennycason** [comment]
I did not know that was a real color until i Googled it. haha

**Comment by kennycason** [comment]
I did this just for you.

![pi_100k_digits_4bit_lsb_cornflower_blue](https://raw.githubusercontent.com/kennycason/number_visualization/master/output/pi_100k_digits_4bit_lsb_cornflower_blue.png)

**Comment by vinchinzu** [comment]
It is a famous scene from 1999 Film Office Space... 
https://www.youtube.com/watch?v=OUoKrdB9BjU
